//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace CarService
{
    using System;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    public partial class Comanda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comanda()
        {
            this.DetaliuComenzi = new HashSet<DetaliuComanda>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string StareComanda { get; set; }
        [DataMember]
        public System.DateTime DataSystem { get; set; }
        [DataMember]
        public System.DateTime DataProgramare { get; set; }
        [DataMember]
        public System.DateTime DataFinalizare { get; set; }
        [DataMember]
        public int KmBord { get; set; }
        [DataMember]
        public string Descriere { get; set; }
        [DataMember]
        public decimal ValoarePiese { get; set; }
        [DataMember]
        public int ClientId { get; set; }
    
        [DataMember]
        public virtual Auto Auto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<DetaliuComanda> DetaliuComenzi { get; set; }
    }
}
