//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace CarService
{
    using System;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    public partial class DetaliuComanda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetaliuComanda()
        {
            this.Mecanici = new HashSet<Mecanic>();
            this.Materiale = new HashSet<Material>();
            this.Imagini = new HashSet<Imagine>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int ComandaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Mecanic> Mecanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Material> Materiale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Imagine> Imagini { get; set; }
        [DataMember]
        public virtual Comanda Comanda { get; set; }
        [DataMember]
        public virtual Operatie Operatie { get; set; }
    }
}
