//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Auto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.Client ClientField;
        
        private int ClientIdField;
        
        private CarService.Comanda[] ComenziField;
        
        private int IdField;
        
        private string NumarAutoField;
        
        private CarService.Sasiu SasiuField;
        
        private string SerieSasiuField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Client Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Comanda[] Comenzi
        {
            get
            {
                return this.ComenziField;
            }
            set
            {
                this.ComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumarAuto
        {
            get
            {
                return this.NumarAutoField;
            }
            set
            {
                this.NumarAutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Sasiu Sasiu
        {
            get
            {
                return this.SasiuField;
            }
            set
            {
                this.SasiuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieSasiu
        {
            get
            {
                return this.SerieSasiuField;
            }
            set
            {
                this.SerieSasiuField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AdresaField;
        
        private string EmailField;
        
        private int IdField;
        
        private string JudetField;
        
        private string LocalitateField;
        
        private CarService.Auto[] MasiniField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        private int TelefonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa
        {
            get
            {
                return this.AdresaField;
            }
            set
            {
                this.AdresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Judet
        {
            get
            {
                return this.JudetField;
            }
            set
            {
                this.JudetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localitate
        {
            get
            {
                return this.LocalitateField;
            }
            set
            {
                this.LocalitateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Auto[] Masini
        {
            get
            {
                return this.MasiniField;
            }
            set
            {
                this.MasiniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefon
        {
            get
            {
                return this.TelefonField;
            }
            set
            {
                this.TelefonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sasiu", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Sasiu : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodSasiuField;
        
        private string DenumireField;
        
        private int IdField;
        
        private CarService.Auto[] MasiniField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodSasiu
        {
            get
            {
                return this.CodSasiuField;
            }
            set
            {
                this.CodSasiuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Auto[] Masini
        {
            get
            {
                return this.MasiniField;
            }
            set
            {
                this.MasiniField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comanda", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Comanda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.Auto AutoField;
        
        private int ClientIdField;
        
        private System.DateTime DataFinalizareField;
        
        private System.DateTime DataProgramareField;
        
        private System.DateTime DataSystemField;
        
        private string DescriereField;
        
        private CarService.DetaliuComanda[] DetaliuComenziField;
        
        private int IdField;
        
        private int KmBordField;
        
        private string StareComandaField;
        
        private decimal ValoarePieseField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Auto Auto
        {
            get
            {
                return this.AutoField;
            }
            set
            {
                this.AutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataFinalizare
        {
            get
            {
                return this.DataFinalizareField;
            }
            set
            {
                this.DataFinalizareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataProgramare
        {
            get
            {
                return this.DataProgramareField;
            }
            set
            {
                this.DataProgramareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataSystem
        {
            get
            {
                return this.DataSystemField;
            }
            set
            {
                this.DataSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.DetaliuComanda[] DetaliuComenzi
        {
            get
            {
                return this.DetaliuComenziField;
            }
            set
            {
                this.DetaliuComenziField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KmBord
        {
            get
            {
                return this.KmBordField;
            }
            set
            {
                this.KmBordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StareComanda
        {
            get
            {
                return this.StareComandaField;
            }
            set
            {
                this.StareComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValoarePiese
        {
            get
            {
                return this.ValoarePieseField;
            }
            set
            {
                this.ValoarePieseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetaliuComanda", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class DetaliuComanda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.Comanda ComandaField;
        
        private int ComandaIdField;
        
        private int IdField;
        
        private CarService.Imagine[] ImaginiField;
        
        private CarService.Material[] MaterialeField;
        
        private CarService.Mecanic[] MecaniciField;
        
        private CarService.Operatie OperatieField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Comanda Comanda
        {
            get
            {
                return this.ComandaField;
            }
            set
            {
                this.ComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComandaId
        {
            get
            {
                return this.ComandaIdField;
            }
            set
            {
                this.ComandaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Imagine[] Imagini
        {
            get
            {
                return this.ImaginiField;
            }
            set
            {
                this.ImaginiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Material[] Materiale
        {
            get
            {
                return this.MaterialeField;
            }
            set
            {
                this.MaterialeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Mecanic[] Mecanici
        {
            get
            {
                return this.MecaniciField;
            }
            set
            {
                this.MecaniciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.Operatie Operatie
        {
            get
            {
                return this.OperatieField;
            }
            set
            {
                this.OperatieField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operatie", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Operatie : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DenumireField;
        
        private CarService.DetaliuComanda DetaliuComandaField;
        
        private int IdField;
        
        private decimal TimpExecutieField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.DetaliuComanda DetaliuComanda
        {
            get
            {
                return this.DetaliuComandaField;
            }
            set
            {
                this.DetaliuComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TimpExecutie
        {
            get
            {
                return this.TimpExecutieField;
            }
            set
            {
                this.TimpExecutieField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagine", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Imagine : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DataField;
        
        private string DescriereField;
        
        private CarService.DetaliuComanda DetaliuComandaField;
        
        private byte[] FotoField;
        
        private int IdField;
        
        private string TitluField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.DetaliuComanda DetaliuComanda
        {
            get
            {
                return this.DetaliuComandaField;
            }
            set
            {
                this.DetaliuComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu
        {
            get
            {
                return this.TitluField;
            }
            set
            {
                this.TitluField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal CantitateField;
        
        private System.DateTime DataAprovizionareField;
        
        private string DenumireField;
        
        private CarService.DetaliuComanda DetaliuComandaField;
        
        private int DetaliuComandaIdField;
        
        private int IdField;
        
        private decimal PretField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantitate
        {
            get
            {
                return this.CantitateField;
            }
            set
            {
                this.CantitateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAprovizionare
        {
            get
            {
                return this.DataAprovizionareField;
            }
            set
            {
                this.DataAprovizionareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denumire
        {
            get
            {
                return this.DenumireField;
            }
            set
            {
                this.DenumireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.DetaliuComanda DetaliuComanda
        {
            get
            {
                return this.DetaliuComandaField;
            }
            set
            {
                this.DetaliuComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetaliuComandaId
        {
            get
            {
                return this.DetaliuComandaIdField;
            }
            set
            {
                this.DetaliuComandaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pret
        {
            get
            {
                return this.PretField;
            }
            set
            {
                this.PretField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mecanic", Namespace="http://schemas.datacontract.org/2004/07/CarService", IsReference=true)]
    public partial class Mecanic : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CarService.DetaliuComanda DetaliuComandaField;
        
        private int DetaliuComandaIdField;
        
        private int IdField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarService.DetaliuComanda DetaliuComanda
        {
            get
            {
                return this.DetaliuComandaField;
            }
            set
            {
                this.DetaliuComandaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetaliuComandaId
        {
            get
            {
                return this.DetaliuComandaIdField;
            }
            set
            {
                this.DetaliuComandaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICarService")]
public interface ICarService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/AddAuto", ReplyAction="http://tempuri.org/InterfaceAuto/AddAutoResponse")]
    void AddAuto(CarService.Auto givenAuto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/AddAuto", ReplyAction="http://tempuri.org/InterfaceAuto/AddAutoResponse")]
    System.Threading.Tasks.Task AddAutoAsync(CarService.Auto givenAuto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetCarsList", ReplyAction="http://tempuri.org/InterfaceAuto/GetCarsListResponse")]
    CarService.Auto[] GetCarsList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetCarsList", ReplyAction="http://tempuri.org/InterfaceAuto/GetCarsListResponse")]
    System.Threading.Tasks.Task<CarService.Auto[]> GetCarsListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAuto", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoResponse")]
    CarService.Auto GetAuto(int autoIndex);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAuto", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoResponse")]
    System.Threading.Tasks.Task<CarService.Auto> GetAutoAsync(int autoIndex);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAutoByAutoNumber", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoByAutoNumberResponse")]
    CarService.Auto GetAutoByAutoNumber(string givenNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/GetAutoByAutoNumber", ReplyAction="http://tempuri.org/InterfaceAuto/GetAutoByAutoNumberResponse")]
    System.Threading.Tasks.Task<CarService.Auto> GetAutoByAutoNumberAsync(string givenNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/UpdateAuto", ReplyAction="http://tempuri.org/InterfaceAuto/UpdateAutoResponse")]
    void UpdateAuto(CarService.Auto givenAuto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/UpdateAuto", ReplyAction="http://tempuri.org/InterfaceAuto/UpdateAutoResponse")]
    System.Threading.Tasks.Task UpdateAutoAsync(CarService.Auto givenAuto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/RemoveAuto", ReplyAction="http://tempuri.org/InterfaceAuto/RemoveAutoResponse")]
    void RemoveAuto(CarService.Auto givenAuto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAuto/RemoveAuto", ReplyAction="http://tempuri.org/InterfaceAuto/RemoveAutoResponse")]
    System.Threading.Tasks.Task RemoveAutoAsync(CarService.Auto givenAuto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/AddClient", ReplyAction="http://tempuri.org/InterfaceClient/AddClientResponse")]
    void AddClient(CarService.Client givenClient);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/AddClient", ReplyAction="http://tempuri.org/InterfaceClient/AddClientResponse")]
    System.Threading.Tasks.Task AddClientAsync(CarService.Client givenClient);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClientList", ReplyAction="http://tempuri.org/InterfaceClient/GetClientListResponse")]
    CarService.Client[] GetClientList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClientList", ReplyAction="http://tempuri.org/InterfaceClient/GetClientListResponse")]
    System.Threading.Tasks.Task<CarService.Client[]> GetClientListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClient", ReplyAction="http://tempuri.org/InterfaceClient/GetClientResponse")]
    CarService.Client GetClient(int clientIndex);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClient", ReplyAction="http://tempuri.org/InterfaceClient/GetClientResponse")]
    System.Threading.Tasks.Task<CarService.Client> GetClientAsync(int clientIndex);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClientByLastName", ReplyAction="http://tempuri.org/InterfaceClient/GetClientByLastNameResponse")]
    CarService.Client[] GetClientByLastName(string lastName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClientByLastName", ReplyAction="http://tempuri.org/InterfaceClient/GetClientByLastNameResponse")]
    System.Threading.Tasks.Task<CarService.Client[]> GetClientByLastNameAsync(string lastName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClientsByCounty", ReplyAction="http://tempuri.org/InterfaceClient/GetClientsByCountyResponse")]
    CarService.Client[] GetClientsByCounty(string givenCounty);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/GetClientsByCounty", ReplyAction="http://tempuri.org/InterfaceClient/GetClientsByCountyResponse")]
    System.Threading.Tasks.Task<CarService.Client[]> GetClientsByCountyAsync(string givenCounty);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/UpdateClient", ReplyAction="http://tempuri.org/InterfaceClient/UpdateClientResponse")]
    void UpdateClient(CarService.Client givenClient);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/UpdateClient", ReplyAction="http://tempuri.org/InterfaceClient/UpdateClientResponse")]
    System.Threading.Tasks.Task UpdateClientAsync(CarService.Client givenClient);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/RemoveClient", ReplyAction="http://tempuri.org/InterfaceClient/RemoveClientResponse")]
    void RemoveClient(CarService.Client givenClient);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceClient/RemoveClient", ReplyAction="http://tempuri.org/InterfaceClient/RemoveClientResponse")]
    System.Threading.Tasks.Task RemoveClientAsync(CarService.Client givenClient);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddCommand", ReplyAction="http://tempuri.org/InterfaceComanda/AddCommandResponse")]
    void AddCommand(CarService.Comanda givenCommand);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/AddCommand", ReplyAction="http://tempuri.org/InterfaceComanda/AddCommandResponse")]
    System.Threading.Tasks.Task AddCommandAsync(CarService.Comanda givenCommand);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetCommands", ReplyAction="http://tempuri.org/InterfaceComanda/GetCommandsResponse")]
    CarService.Comanda[] GetCommands();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetCommands", ReplyAction="http://tempuri.org/InterfaceComanda/GetCommandsResponse")]
    System.Threading.Tasks.Task<CarService.Comanda[]> GetCommandsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetCommand", ReplyAction="http://tempuri.org/InterfaceComanda/GetCommandResponse")]
    CarService.Comanda GetCommand(int commandIndex);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/GetCommand", ReplyAction="http://tempuri.org/InterfaceComanda/GetCommandResponse")]
    System.Threading.Tasks.Task<CarService.Comanda> GetCommandAsync(int commandIndex);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/UpdateCommand", ReplyAction="http://tempuri.org/InterfaceComanda/UpdateCommandResponse")]
    void UpdateCommand(CarService.Comanda givenComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/UpdateCommand", ReplyAction="http://tempuri.org/InterfaceComanda/UpdateCommandResponse")]
    System.Threading.Tasks.Task UpdateCommandAsync(CarService.Comanda givenComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/RemoveCommand", ReplyAction="http://tempuri.org/InterfaceComanda/RemoveCommandResponse")]
    void RemoveCommand(CarService.Comanda givenComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceComanda/RemoveCommand", ReplyAction="http://tempuri.org/InterfaceComanda/RemoveCommandResponse")]
    System.Threading.Tasks.Task RemoveCommandAsync(CarService.Comanda givenComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/AddCommandDetail", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/AddCommandDetailResponse")]
    void AddCommandDetail(CarService.DetaliuComanda givenDetaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/AddCommandDetail", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/AddCommandDetailResponse")]
    System.Threading.Tasks.Task AddCommandDetailAsync(CarService.DetaliuComanda givenDetaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/GetCommandsDetailsList", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/GetCommandsDetailsListResponse")]
    CarService.DetaliuComanda[] GetCommandsDetailsList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/GetCommandsDetailsList", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/GetCommandsDetailsListResponse")]
    System.Threading.Tasks.Task<CarService.DetaliuComanda[]> GetCommandsDetailsListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/GetCommandDetail", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/GetCommandDetailResponse")]
    CarService.DetaliuComanda GetCommandDetail(int commandDetailId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/GetCommandDetail", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/GetCommandDetailResponse")]
    System.Threading.Tasks.Task<CarService.DetaliuComanda> GetCommandDetailAsync(int commandDetailId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/RemoveCommandDetail", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/RemoveCommandDetailResponse")]
    void RemoveCommandDetail(CarService.DetaliuComanda givenDetaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDetaliuComanda/RemoveCommandDetail", ReplyAction="http://tempuri.org/InterfaceDetaliuComanda/RemoveCommandDetailResponse")]
    System.Threading.Tasks.Task RemoveCommandDetailAsync(CarService.DetaliuComanda givenDetaliuComanda);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/AddSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/AddSasiuResponse")]
    void AddSasiu(CarService.Sasiu givenSasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/AddSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/AddSasiuResponse")]
    System.Threading.Tasks.Task AddSasiuAsync(CarService.Sasiu givenSasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasiuriList", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiuriListResponse")]
    CarService.Sasiu[] GetSasiuriList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasiuriList", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiuriListResponse")]
    System.Threading.Tasks.Task<CarService.Sasiu[]> GetSasiuriListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiuResponse")]
    CarService.Sasiu GetSasiu(int sasiuIndex);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiuResponse")]
    System.Threading.Tasks.Task<CarService.Sasiu> GetSasiuAsync(int sasiuIndex);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasiuByCode", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiuByCodeResponse")]
    CarService.Sasiu GetSasiuByCode(string codeSasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/GetSasiuByCode", ReplyAction="http://tempuri.org/InterfaceSasiu/GetSasiuByCodeResponse")]
    System.Threading.Tasks.Task<CarService.Sasiu> GetSasiuByCodeAsync(string codeSasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/UpdateSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/UpdateSasiuResponse")]
    void UpdateSasiu(CarService.Sasiu givenSasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/UpdateSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/UpdateSasiuResponse")]
    System.Threading.Tasks.Task UpdateSasiuAsync(CarService.Sasiu givenSasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/RemoveSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/RemoveSasiuResponse")]
    void RemoveSasiu(CarService.Sasiu givenSasiu);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceSasiu/RemoveSasiu", ReplyAction="http://tempuri.org/InterfaceSasiu/RemoveSasiuResponse")]
    System.Threading.Tasks.Task RemoveSasiuAsync(CarService.Sasiu givenSasiu);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICarServiceChannel : ICarService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CarServiceClient : System.ServiceModel.ClientBase<ICarService>, ICarService
{
    
    public CarServiceClient()
    {
    }
    
    public CarServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CarServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddAuto(CarService.Auto givenAuto)
    {
        base.Channel.AddAuto(givenAuto);
    }
    
    public System.Threading.Tasks.Task AddAutoAsync(CarService.Auto givenAuto)
    {
        return base.Channel.AddAutoAsync(givenAuto);
    }
    
    public CarService.Auto[] GetCarsList()
    {
        return base.Channel.GetCarsList();
    }
    
    public System.Threading.Tasks.Task<CarService.Auto[]> GetCarsListAsync()
    {
        return base.Channel.GetCarsListAsync();
    }
    
    public CarService.Auto GetAuto(int autoIndex)
    {
        return base.Channel.GetAuto(autoIndex);
    }
    
    public System.Threading.Tasks.Task<CarService.Auto> GetAutoAsync(int autoIndex)
    {
        return base.Channel.GetAutoAsync(autoIndex);
    }
    
    public CarService.Auto GetAutoByAutoNumber(string givenNumber)
    {
        return base.Channel.GetAutoByAutoNumber(givenNumber);
    }
    
    public System.Threading.Tasks.Task<CarService.Auto> GetAutoByAutoNumberAsync(string givenNumber)
    {
        return base.Channel.GetAutoByAutoNumberAsync(givenNumber);
    }
    
    public void UpdateAuto(CarService.Auto givenAuto)
    {
        base.Channel.UpdateAuto(givenAuto);
    }
    
    public System.Threading.Tasks.Task UpdateAutoAsync(CarService.Auto givenAuto)
    {
        return base.Channel.UpdateAutoAsync(givenAuto);
    }
    
    public void RemoveAuto(CarService.Auto givenAuto)
    {
        base.Channel.RemoveAuto(givenAuto);
    }
    
    public System.Threading.Tasks.Task RemoveAutoAsync(CarService.Auto givenAuto)
    {
        return base.Channel.RemoveAutoAsync(givenAuto);
    }
    
    public void AddClient(CarService.Client givenClient)
    {
        base.Channel.AddClient(givenClient);
    }
    
    public System.Threading.Tasks.Task AddClientAsync(CarService.Client givenClient)
    {
        return base.Channel.AddClientAsync(givenClient);
    }
    
    public CarService.Client[] GetClientList()
    {
        return base.Channel.GetClientList();
    }
    
    public System.Threading.Tasks.Task<CarService.Client[]> GetClientListAsync()
    {
        return base.Channel.GetClientListAsync();
    }
    
    public CarService.Client GetClient(int clientIndex)
    {
        return base.Channel.GetClient(clientIndex);
    }
    
    public System.Threading.Tasks.Task<CarService.Client> GetClientAsync(int clientIndex)
    {
        return base.Channel.GetClientAsync(clientIndex);
    }
    
    public CarService.Client[] GetClientByLastName(string lastName)
    {
        return base.Channel.GetClientByLastName(lastName);
    }
    
    public System.Threading.Tasks.Task<CarService.Client[]> GetClientByLastNameAsync(string lastName)
    {
        return base.Channel.GetClientByLastNameAsync(lastName);
    }
    
    public CarService.Client[] GetClientsByCounty(string givenCounty)
    {
        return base.Channel.GetClientsByCounty(givenCounty);
    }
    
    public System.Threading.Tasks.Task<CarService.Client[]> GetClientsByCountyAsync(string givenCounty)
    {
        return base.Channel.GetClientsByCountyAsync(givenCounty);
    }
    
    public void UpdateClient(CarService.Client givenClient)
    {
        base.Channel.UpdateClient(givenClient);
    }
    
    public System.Threading.Tasks.Task UpdateClientAsync(CarService.Client givenClient)
    {
        return base.Channel.UpdateClientAsync(givenClient);
    }
    
    public void RemoveClient(CarService.Client givenClient)
    {
        base.Channel.RemoveClient(givenClient);
    }
    
    public System.Threading.Tasks.Task RemoveClientAsync(CarService.Client givenClient)
    {
        return base.Channel.RemoveClientAsync(givenClient);
    }
    
    public void AddCommand(CarService.Comanda givenCommand)
    {
        base.Channel.AddCommand(givenCommand);
    }
    
    public System.Threading.Tasks.Task AddCommandAsync(CarService.Comanda givenCommand)
    {
        return base.Channel.AddCommandAsync(givenCommand);
    }
    
    public CarService.Comanda[] GetCommands()
    {
        return base.Channel.GetCommands();
    }
    
    public System.Threading.Tasks.Task<CarService.Comanda[]> GetCommandsAsync()
    {
        return base.Channel.GetCommandsAsync();
    }
    
    public CarService.Comanda GetCommand(int commandIndex)
    {
        return base.Channel.GetCommand(commandIndex);
    }
    
    public System.Threading.Tasks.Task<CarService.Comanda> GetCommandAsync(int commandIndex)
    {
        return base.Channel.GetCommandAsync(commandIndex);
    }
    
    public void UpdateCommand(CarService.Comanda givenComanda)
    {
        base.Channel.UpdateCommand(givenComanda);
    }
    
    public System.Threading.Tasks.Task UpdateCommandAsync(CarService.Comanda givenComanda)
    {
        return base.Channel.UpdateCommandAsync(givenComanda);
    }
    
    public void RemoveCommand(CarService.Comanda givenComanda)
    {
        base.Channel.RemoveCommand(givenComanda);
    }
    
    public System.Threading.Tasks.Task RemoveCommandAsync(CarService.Comanda givenComanda)
    {
        return base.Channel.RemoveCommandAsync(givenComanda);
    }
    
    public void AddCommandDetail(CarService.DetaliuComanda givenDetaliuComanda)
    {
        base.Channel.AddCommandDetail(givenDetaliuComanda);
    }
    
    public System.Threading.Tasks.Task AddCommandDetailAsync(CarService.DetaliuComanda givenDetaliuComanda)
    {
        return base.Channel.AddCommandDetailAsync(givenDetaliuComanda);
    }
    
    public CarService.DetaliuComanda[] GetCommandsDetailsList()
    {
        return base.Channel.GetCommandsDetailsList();
    }
    
    public System.Threading.Tasks.Task<CarService.DetaliuComanda[]> GetCommandsDetailsListAsync()
    {
        return base.Channel.GetCommandsDetailsListAsync();
    }
    
    public CarService.DetaliuComanda GetCommandDetail(int commandDetailId)
    {
        return base.Channel.GetCommandDetail(commandDetailId);
    }
    
    public System.Threading.Tasks.Task<CarService.DetaliuComanda> GetCommandDetailAsync(int commandDetailId)
    {
        return base.Channel.GetCommandDetailAsync(commandDetailId);
    }
    
    public void RemoveCommandDetail(CarService.DetaliuComanda givenDetaliuComanda)
    {
        base.Channel.RemoveCommandDetail(givenDetaliuComanda);
    }
    
    public System.Threading.Tasks.Task RemoveCommandDetailAsync(CarService.DetaliuComanda givenDetaliuComanda)
    {
        return base.Channel.RemoveCommandDetailAsync(givenDetaliuComanda);
    }
    
    public void AddSasiu(CarService.Sasiu givenSasiu)
    {
        base.Channel.AddSasiu(givenSasiu);
    }
    
    public System.Threading.Tasks.Task AddSasiuAsync(CarService.Sasiu givenSasiu)
    {
        return base.Channel.AddSasiuAsync(givenSasiu);
    }
    
    public CarService.Sasiu[] GetSasiuriList()
    {
        return base.Channel.GetSasiuriList();
    }
    
    public System.Threading.Tasks.Task<CarService.Sasiu[]> GetSasiuriListAsync()
    {
        return base.Channel.GetSasiuriListAsync();
    }
    
    public CarService.Sasiu GetSasiu(int sasiuIndex)
    {
        return base.Channel.GetSasiu(sasiuIndex);
    }
    
    public System.Threading.Tasks.Task<CarService.Sasiu> GetSasiuAsync(int sasiuIndex)
    {
        return base.Channel.GetSasiuAsync(sasiuIndex);
    }
    
    public CarService.Sasiu GetSasiuByCode(string codeSasiu)
    {
        return base.Channel.GetSasiuByCode(codeSasiu);
    }
    
    public System.Threading.Tasks.Task<CarService.Sasiu> GetSasiuByCodeAsync(string codeSasiu)
    {
        return base.Channel.GetSasiuByCodeAsync(codeSasiu);
    }
    
    public void UpdateSasiu(CarService.Sasiu givenSasiu)
    {
        base.Channel.UpdateSasiu(givenSasiu);
    }
    
    public System.Threading.Tasks.Task UpdateSasiuAsync(CarService.Sasiu givenSasiu)
    {
        return base.Channel.UpdateSasiuAsync(givenSasiu);
    }
    
    public void RemoveSasiu(CarService.Sasiu givenSasiu)
    {
        base.Channel.RemoveSasiu(givenSasiu);
    }
    
    public System.Threading.Tasks.Task RemoveSasiuAsync(CarService.Sasiu givenSasiu)
    {
        return base.Channel.RemoveSasiuAsync(givenSasiu);
    }
}
